#!/usr/bin/env python
__author__ = 'Mart Hytt'


class ActionConstants:
    NODE_SATELLITE_MANAGE = 'SATELLITE_MANAGE'
    NODE_PUBLIC_CALC = 'PUBLIC_CALC'
    NODE_COMMUNICATION = 'COMMUNICATION'
    NODE_UTF_CONTROLLER = 'UTF_CONTROLLER'

    ACTION_NEXT_FLYOVER = 'NEXT_FLYOVER'
    ACTION_CALCULATE_VALUES = 'CALCULATE_VALUES'

    ACTION_ADD_ID = 'ADD_ID'
    ACTION_REMOVE_ID = 'REMOVE_ID'
    ACTION_REMOVE_ALL_IDS = 'REMOVE_ALL_IDS'

    ACTION_MOVE = 'MOVE'
    ACTION_REMOTE_MOVE = 'REMOTE_MOVE'
    ACTION_GET_ORIENTATION = 'GET_ORIENTATION'

    ACTION_SET_FREQUENCY = 'SET_FREQUENCY'
    ACTION_SWITCH = 'SWITCH'
